from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    INVESTIGATOR = "INVESTIGATOR"


class CaseStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class RecordType(str, Enum):
    CDR = "CDR"
    TRANSACTION = "TRANSACTION"


class EntityType(str, Enum):
    PERSON = "PERSON"
    PHONE = "PHONE"
    BANK_ACCOUNT = "BANK_ACCOUNT"
    VEHICLE = "VEHICLE"
    ORGANIZATION = "ORGANIZATION"
    LOCATION = "LOCATION"
    EVENT = "EVENT"


class RelationshipType(str, Enum):
    CALLED = "CALLED"
    SENT_MONEY_TO = "SENT_MONEY_TO"
    OWNS_VEHICLE = "OWNS_VEHICLE"
    USED_VEHICLE = "USED_VEHICLE"
    WORKS_FOR = "WORKS_FOR"
    LOCATED_AT = "LOCATED_AT"
    ASSOCIATED_WITH = "ASSOCIATED_WITH"
    PART_OF_EVENT = "PART_OF_EVENT"


class RelationshipStatus(str, Enum):
    CONFIRMED = "CONFIRMED"
    INFERRED = "INFERRED"
    PREDICTED = "PREDICTED"


class AuditAction(str, Enum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    CASE_ACCESS_GRANTED = "CASE_ACCESS_GRANTED"
    CASE_ACCESS_DENIED = "CASE_ACCESS_DENIED"
    CASE_CREATED = "CASE_CREATED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_VIEWED = "DOCUMENT_VIEWED"
    DOCUMENT_PROCESSED = "DOCUMENT_PROCESSED"
    DOCUMENT_PROCESS_FAILED = "DOCUMENT_PROCESS_FAILED"
    EVIDENCE_ANCHORED = "EVIDENCE_ANCHORED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    INVESTIGATION_PATH_QUERIED = "INVESTIGATION_PATH_QUERIED"


class AuditResult(str, Enum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
