"""Phase 11 — Schema Validation & Contract Testing for CrimeLens ML Pipeline.

Verifies that ML outputs strictly follow frozen contract schemas:
- EntityMention
- Relationship
- ResolutionProposal
- Pattern
- Lead
- ExtractionResult

Guarantees:
- Zero database UUIDs generated by ML.
- Zero case_id generated by ML.
- Zero direct database / Neo4j access.
- No guilt determination or criminal prediction.
- No 'DETECTED' status.
- Strict extra="forbid" field enforcement.
- Safe JSON serialization and round-trip fidelity.
"""

from __future__ import annotations

from datetime import datetime, timezone
import json
import unittest

from pydantic import ValidationError

from ml.config import MLConfig
from ml.pipeline import process_document
from ml.validation import (
    validate_entity_mention,
    validate_extraction_result,
    validate_lead,
    validate_pattern,
    validate_relationship,
    validate_resolution_proposal,
)
from shared.schemas.enums import (
    EntityType,
    LeadPriority,
    LeadStatus,
    LeadType,
    PatternType,
    RelationshipStatus,
    RelationshipType,
    ResolutionSignal,
    Severity,
)
from shared.schemas.models import (
    EntityMention,
    ExtractionResult,
    Lead,
    Pattern,
    Relationship,
    ResolutionProposal,
)


class TestEntityMentionContract(unittest.TestCase):
    """Contract tests for EntityMention model and schema."""

    def test_all_valid_entity_types(self):
        valid_types = [
            EntityType.PERSON,
            EntityType.PHONE,
            EntityType.BANK_ACCOUNT,
            EntityType.VEHICLE,
            EntityType.ORGANIZATION,
            EntityType.LOCATION,
            EntityType.EVENT,
        ]
        for idx, et in enumerate(valid_types):
            mention = EntityMention(
                id=f"mention_{idx:03d}",
                type=et,
                name=f"Sample {et.value}",
                confidence=0.95,
            )
            validated = validate_entity_mention(mention)
            self.assertEqual(validated.type, et)

    def test_prohibited_entity_types_rejected(self):
        prohibited = [
            "CRIMINAL",
            "SUSPECT",
            "RISK_PERSON",
            "CRIMINAL_ORGANIZATION",
            "HUMAN",
            "DEVICE",
            "UNKNOWN",
        ]
        for bad_type in prohibited:
            with self.assertRaises(ValidationError, msg=f"Prohibited type '{bad_type}' should fail"):
                EntityMention.model_validate({
                    "id": "mention_001",
                    "type": bad_type,
                    "name": "Target",
                    "confidence": 0.9,
                })

    def test_entity_required_fields_missing(self):
        base = {"id": "m_1", "type": "PERSON", "name": "Alice", "confidence": 0.9}
        for field in ["id", "type", "name", "confidence"]:
            payload = dict(base)
            del payload[field]
            with self.assertRaises(ValidationError, msg=f"Missing {field} must fail"):
                EntityMention.model_validate(payload)

    def test_entity_empty_strings_rejected(self):
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "", "type": "PERSON", "name": "Alice", "confidence": 0.9})
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m_1", "type": "PERSON", "name": "", "confidence": 0.9})

    def test_entity_confidence_boundaries(self):
        # 0.0, 0.5, 1.0 are valid
        for valid_conf in [0.0, 0.5, 1.0]:
            m = EntityMention(id="m_1", type=EntityType.PERSON, name="Alice", confidence=valid_conf)
            self.assertEqual(m.confidence, valid_conf)

        # < 0.0 is invalid
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m_1", "type": "PERSON", "name": "Alice", "confidence": -0.01})

        # > 1.0 is invalid
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m_1", "type": "PERSON", "name": "Alice", "confidence": 1.01})

        # Percentage format (e.g. 95) is invalid
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m_1", "type": "PERSON", "name": "Alice", "confidence": 95})

    def test_entity_extra_fields_forbidden(self):
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({
                "id": "m_1",
                "type": "PERSON",
                "name": "Alice",
                "confidence": 0.9,
                "extra_field": "disallowed",
            })
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({
                "id": "m_1",
                "type": "PERSON",
                "name": "Alice",
                "confidence": 0.9,
                "criminal_score": 0.8,
            })


class TestRelationshipContract(unittest.TestCase):
    """Contract tests for Relationship model and schema."""

    def test_all_valid_relationship_types(self):
        valid_types = [
            RelationshipType.CALLED,
            RelationshipType.SENT_MONEY_TO,
            RelationshipType.OWNS_VEHICLE,
            RelationshipType.USED_VEHICLE,
            RelationshipType.WORKS_FOR,
            RelationshipType.LOCATED_AT,
            RelationshipType.ASSOCIATED_WITH,
            RelationshipType.PART_OF_EVENT,
        ]
        now = datetime.now(timezone.utc)
        for idx, rt in enumerate(valid_types):
            rel = Relationship(
                id=f"rel_{idx:03d}",
                source_entity_id="mention_001",
                relationship=rt,
                target_entity_id="mention_002",
                confidence=0.85,
                status=RelationshipStatus.INFERRED,
                source_document_id="doc_001",
                evidence_snippet="Evidence snippet text",
                extracted_at=now,
            )
            validated = validate_relationship(rel)
            self.assertEqual(validated.relationship, rt)

    def test_prohibited_relationship_types_rejected(self):
        prohibited = ["KNOWS", "MET_WITH", "CRIMINAL_COLLUSION", "SUSPECTED_OF", "TRANSACTED"]
        now = datetime.now(timezone.utc).isoformat()
        for bad_type in prohibited:
            with self.assertRaises(ValidationError, msg=f"Prohibited type '{bad_type}' should fail"):
                Relationship.model_validate({
                    "id": "rel_001",
                    "source_entity_id": "m_1",
                    "relationship": bad_type,
                    "target_entity_id": "m_2",
                    "confidence": 0.8,
                    "status": "INFERRED",
                    "source_document_id": "doc_001",
                    "evidence_snippet": "test",
                    "extracted_at": now,
                })

    def test_directionality_preservation(self):
        now = datetime.now(timezone.utc)
        rel1 = Relationship(
            id="rel_001",
            source_entity_id="mention_001",
            relationship=RelationshipType.SENT_MONEY_TO,
            target_entity_id="mention_002",
            confidence=0.9,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_001",
            evidence_snippet="A sent money to B",
            extracted_at=now,
        )
        rel2 = Relationship(
            id="rel_002",
            source_entity_id="mention_002",
            relationship=RelationshipType.SENT_MONEY_TO,
            target_entity_id="mention_001",
            confidence=0.9,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_001",
            evidence_snippet="B sent money to A",
            extracted_at=now,
        )
        self.assertNotEqual(rel1.source_entity_id, rel2.source_entity_id)
        self.assertNotEqual(rel1.target_entity_id, rel2.target_entity_id)
        # Serialization preserves direction
        json_data = json.loads(rel1.model_dump_json())
        self.assertEqual(json_data["source_entity_id"], "mention_001")
        self.assertEqual(json_data["target_entity_id"], "mention_002")

    def test_relationship_status_validation(self):
        now = datetime.now(timezone.utc).isoformat()
        base = {
            "id": "rel_001",
            "source_entity_id": "m_1",
            "relationship": "CALLED",
            "target_entity_id": "m_2",
            "confidence": 0.8,
            "source_document_id": "doc_001",
            "evidence_snippet": "test",
            "extracted_at": now,
        }
        for st in ["CONFIRMED", "INFERRED", "PREDICTED"]:
            payload = dict(base, status=st)
            rel = Relationship.model_validate(payload)
            self.assertEqual(rel.status.value, st)

        # DETECTED is strictly rejected
        with self.assertRaises(ValidationError):
            Relationship.model_validate(dict(base, status="DETECTED"))

        # INFERRED is not coerced to CONFIRMED
        rel_inferred = Relationship.model_validate(dict(base, status="INFERRED"))
        self.assertEqual(rel_inferred.status, RelationshipStatus.INFERRED)
        self.assertNotEqual(rel_inferred.status, RelationshipStatus.CONFIRMED)

    def test_relationship_provenance_requirement(self):
        now = datetime.now(timezone.utc).isoformat()
        base = {
            "id": "rel_001",
            "source_entity_id": "m_1",
            "relationship": "CALLED",
            "target_entity_id": "m_2",
            "confidence": 0.8,
            "status": "INFERRED",
            "evidence_snippet": "test",
            "extracted_at": now,
        }
        # Neither source_document_id nor source_record_id provided
        with self.assertRaises(ValidationError):
            Relationship.model_validate(base)

        # source_document_id only -> valid
        r1 = Relationship.model_validate(dict(base, source_document_id="doc_001"))
        self.assertEqual(r1.source_document_id, "doc_001")

        # source_record_id only -> valid
        r2 = Relationship.model_validate(dict(base, source_record_id="rec_001"))
        self.assertEqual(r2.source_record_id, "rec_001")

    def test_relationship_extra_fields_forbidden(self):
        now = datetime.now(timezone.utc).isoformat()
        # Structured record fields must NOT bleed into Relationship contract
        for forbidden_field in ["amount", "currency", "call_time", "duration", "case_id"]:
            payload = {
                "id": "rel_001",
                "source_entity_id": "m_1",
                "relationship": "SENT_MONEY_TO",
                "target_entity_id": "m_2",
                "confidence": 0.9,
                "status": "INFERRED",
                "source_document_id": "doc_001",
                "evidence_snippet": "test",
                "extracted_at": now,
                forbidden_field: 1000,
            }
            with self.assertRaises(ValidationError, msg=f"Field '{forbidden_field}' must be rejected"):
                Relationship.model_validate(payload)


class TestResolutionProposalContract(unittest.TestCase):
    """Contract tests for ResolutionProposal model and schema."""

    def test_valid_resolution_proposal(self):
        prop = ResolutionProposal(
            canonical_entity_id="entity_001",
            mention_id="mention_002",
            confidence=0.92,
            signals=[ResolutionSignal.NAME_SIMILARITY, ResolutionSignal.PHONE_MATCH],
        )
        validated = validate_resolution_proposal(prop)
        self.assertEqual(validated.canonical_entity_id, "entity_001")
        self.assertEqual(len(validated.signals), 2)

    def test_all_valid_resolution_signals(self):
        signals = [
            ResolutionSignal.NAME_SIMILARITY,
            ResolutionSignal.PHONE_MATCH,
            ResolutionSignal.ACCOUNT_MATCH,
            ResolutionSignal.VEHICLE_MATCH,
            ResolutionSignal.LOCATION_MATCH,
            ResolutionSignal.ORGANIZATION_MATCH,
        ]
        for sig in signals:
            prop = ResolutionProposal(
                canonical_entity_id="entity_001",
                mention_id="mention_002",
                confidence=0.88,
                signals=[sig],
            )
            self.assertEqual(prop.signals[0], sig)

    def test_invalid_resolution_signal_rejected(self):
        for bad_sig in ["fingerprint_match", "dna_match", "criminal_record", "face_match"]:
            with self.assertRaises(ValidationError):
                ResolutionProposal.model_validate({
                    "canonical_entity_id": "entity_001",
                    "mention_id": "mention_002",
                    "confidence": 0.85,
                    "signals": [bad_sig],
                })

    def test_empty_signals_rejected(self):
        with self.assertRaises(ValidationError):
            ResolutionProposal.model_validate({
                "canonical_entity_id": "entity_001",
                "mention_id": "mention_002",
                "confidence": 0.85,
                "signals": [],
            })

    def test_resolution_is_proposal_not_db_merge(self):
        # Name-only match proposal
        prop = ResolutionProposal(
            canonical_entity_id="entity_fuzzy_001",
            mention_id="mention_003",
            confidence=0.75,
            signals=[ResolutionSignal.NAME_SIMILARITY],
        )
        self.assertEqual(prop.signals, [ResolutionSignal.NAME_SIMILARITY])
        # It has NO database merge fields or status
        payload = prop.model_dump()
        self.assertNotIn("status", payload)
        self.assertNotIn("database_uuid", payload)
        self.assertNotIn("is_merged", payload)

        # Attempting to add DB merge attributes fails extra="forbid"
        with self.assertRaises(ValidationError):
            ResolutionProposal.model_validate(dict(payload, is_merged=True))
        with self.assertRaises(ValidationError):
            ResolutionProposal.model_validate(dict(payload, database_uuid="123e4567-e89b-12d3-a456-426614174000"))


class TestPatternContract(unittest.TestCase):
    """Contract tests for Pattern model and schema."""

    def test_all_valid_pattern_types(self):
        valid_types = [
            PatternType.CIRCULAR_TRANSACTION,
            PatternType.RAPID_TRANSFER_CHAIN,
            PatternType.LOCATION_TIME_OVERLAP,
        ]
        for idx, pt in enumerate(valid_types):
            pat = Pattern(
                id=f"pat_{idx:03d}",
                type=pt,
                severity=Severity.HIGH,
                status=RelationshipStatus.INFERRED,
                entities=["ent_1", "ent_2"],
                explanation="Suspicious pattern detected",
                evidence_ids=["ev_1", "ev_2"],
            )
            validated = validate_pattern(pat)
            self.assertEqual(validated.type, pt)

    def test_invalid_pattern_type_rejected(self):
        prohibited = ["MONEY_LAUNDERING", "STRUCTURING", "TERRORIST_FINANCING", "GANG_NETWORK"]
        for bad_type in prohibited:
            with self.assertRaises(ValidationError):
                Pattern.model_validate({
                    "id": "pat_001",
                    "type": bad_type,
                    "severity": "HIGH",
                    "status": "INFERRED",
                    "entities": ["ent_1"],
                    "explanation": "test",
                    "evidence_ids": ["ev_1"],
                })

    def test_pattern_severity_contract(self):
        base = {
            "id": "pat_001",
            "type": "CIRCULAR_TRANSACTION",
            "status": "INFERRED",
            "entities": ["ent_1"],
            "explanation": "test",
            "evidence_ids": ["ev_1"],
        }
        for sev in ["LOW", "MEDIUM", "HIGH"]:
            p = Pattern.model_validate(dict(base, severity=sev))
            self.assertEqual(p.severity.value, sev)

        # Prohibited severities
        for bad_sev in ["CRITICAL", "SEVERE", "URGENT"]:
            with self.assertRaises(ValidationError):
                Pattern.model_validate(dict(base, severity=bad_sev))

    def test_pattern_status_contract(self):
        base = {
            "id": "pat_001",
            "type": "CIRCULAR_TRANSACTION",
            "severity": "HIGH",
            "entities": ["ent_1"],
            "explanation": "test",
            "evidence_ids": ["ev_1"],
        }
        # DETECTED must be rejected
        with self.assertRaises(ValidationError):
            Pattern.model_validate(dict(base, status="DETECTED"))

        # INFERRED is valid and preserved
        p = Pattern.model_validate(dict(base, status="INFERRED"))
        self.assertEqual(p.status, RelationshipStatus.INFERRED)
        self.assertNotEqual(p.status, RelationshipStatus.CONFIRMED)

    def test_pattern_no_confidence_field(self):
        # Pattern contract in shared schemas does NOT have a confidence field
        payload = {
            "id": "pat_001",
            "type": "CIRCULAR_TRANSACTION",
            "severity": "HIGH",
            "status": "INFERRED",
            "entities": ["ent_1"],
            "explanation": "test",
            "evidence_ids": ["ev_1"],
            "confidence": 0.95,
        }
        with self.assertRaises(ValidationError):
            Pattern.model_validate(payload)

    def test_pattern_min_lengths(self):
        base = {
            "id": "pat_001",
            "type": "CIRCULAR_TRANSACTION",
            "severity": "HIGH",
            "status": "INFERRED",
            "entities": ["ent_1"],
            "explanation": "test",
            "evidence_ids": ["ev_1"],
        }
        # Empty entities list rejected
        with self.assertRaises(ValidationError):
            Pattern.model_validate(dict(base, entities=[]))
        # Empty evidence_ids list rejected
        with self.assertRaises(ValidationError):
            Pattern.model_validate(dict(base, evidence_ids=[]))
        # Empty explanation string rejected
        with self.assertRaises(ValidationError):
            Pattern.model_validate(dict(base, explanation=""))


class TestLeadContract(unittest.TestCase):
    """Contract tests for Lead model and schema."""

    def test_all_valid_lead_types(self):
        valid_types = [
            LeadType.FINANCIAL_NETWORK,
            LeadType.CIRCULAR_TRANSACTION,
            LeadType.RAPID_TRANSFER_CHAIN,
            LeadType.LOCATION_TIME_OVERLAP,
            LeadType.CROSS_CASE,
        ]
        for idx, lt in enumerate(valid_types):
            lead = Lead(
                id=f"lead_{idx:03d}",
                type=lt,
                priority=LeadPriority.MEDIUM,
                status=LeadStatus.REVIEW_REQUIRED,
                title=f"Lead {lt.value}",
                explanation="Investigate transaction pattern",
                entity_ids=["ent_1"],
                evidence_ids=["ev_1"],
            )
            validated = validate_lead(lead)
            self.assertEqual(validated.type, lt)

    def test_lead_priority_contract(self):
        base = {
            "id": "lead_001",
            "type": "FINANCIAL_NETWORK",
            "title": "Test Lead",
            "explanation": "Test explanation",
            "entity_ids": ["ent_1"],
            "evidence_ids": ["ev_1"],
        }
        # Valid priorities: LOW, MEDIUM, HIGH
        for prio in ["LOW", "MEDIUM", "HIGH"]:
            lead = Lead.model_validate(dict(base, priority=prio))
            self.assertEqual(lead.priority.value, prio)

        # Prohibited priorities: CRITICAL, SEVERE, URGENT
        for bad_prio in ["CRITICAL", "SEVERE", "URGENT"]:
            with self.assertRaises(ValidationError):
                Lead.model_validate(dict(base, priority=bad_prio))

    def test_lead_status_only_review_required(self):
        base = {
            "id": "lead_001",
            "type": "FINANCIAL_NETWORK",
            "priority": "HIGH",
            "title": "Test Lead",
            "explanation": "Test explanation",
            "entity_ids": ["ent_1"],
            "evidence_ids": ["ev_1"],
        }
        lead = Lead.model_validate(base)
        self.assertEqual(lead.status, LeadStatus.REVIEW_REQUIRED)

        # DETECTED, CONFIRMED, PREDICTED are NOT valid LeadStatus values
        for bad_st in ["DETECTED", "CONFIRMED", "PREDICTED", "CLOSED"]:
            with self.assertRaises(ValidationError):
                Lead.model_validate(dict(base, status=bad_st))

    def test_lead_no_severity_field(self):
        payload = {
            "id": "lead_001",
            "type": "FINANCIAL_NETWORK",
            "priority": "HIGH",
            "title": "Test Lead",
            "explanation": "Test explanation",
            "entity_ids": ["ent_1"],
            "evidence_ids": ["ev_1"],
            "severity": "HIGH",
        }
        with self.assertRaises(ValidationError):
            Lead.model_validate(payload)

    def test_lead_no_confidence_field(self):
        payload = {
            "id": "lead_001",
            "type": "FINANCIAL_NETWORK",
            "priority": "HIGH",
            "title": "Test Lead",
            "explanation": "Test explanation",
            "entity_ids": ["ent_1"],
            "evidence_ids": ["ev_1"],
            "confidence": 0.9,
        }
        with self.assertRaises(ValidationError):
            Lead.model_validate(payload)

    def test_lead_priority_score_boundaries(self):
        base = {
            "id": "lead_001",
            "type": "FINANCIAL_NETWORK",
            "priority": "HIGH",
            "title": "Test Lead",
            "explanation": "Test explanation",
            "entity_ids": ["ent_1"],
            "evidence_ids": ["ev_1"],
        }
        # 0.0, 1.0, 0.5 valid
        for sc in [0.0, 0.5, 1.0]:
            lead = Lead.model_validate(dict(base, priority_score=sc))
            self.assertEqual(lead.priority_score, sc)

        # None is valid
        lead_none = Lead.model_validate(dict(base, priority_score=None))
        self.assertIsNone(lead_none.priority_score)

        # < 0.0 or > 1.0 invalid
        with self.assertRaises(ValidationError):
            Lead.model_validate(dict(base, priority_score=-0.01))
        with self.assertRaises(ValidationError):
            Lead.model_validate(dict(base, priority_score=1.01))

    def test_lead_explanation_non_accusatory(self):
        lead = Lead(
            id="lead_001",
            type=LeadType.CIRCULAR_TRANSACTION,
            priority=LeadPriority.HIGH,
            title="Potential circular transaction pattern",
            explanation="Funds move in a closed loop among 3 accounts within 14 days.",
            entity_ids=["acc_1", "acc_2", "acc_3"],
            evidence_ids=["txn_1", "txn_2", "txn_3"],
        )
        prohibited_words = ["guilty", "criminal suspect", "perpetrator", "convicted", "conspiracy guilty"]
        text = (lead.title + " " + lead.explanation).lower()
        for word in prohibited_words:
            self.assertNotIn(word, text, msg=f"Prohibited guilt term '{word}' found in lead")


class TestExtractionResultContract(unittest.TestCase):
    """Contract tests for ExtractionResult model and envelope referential integrity."""

    def test_valid_complete_extraction_result(self):
        now = datetime.now(timezone.utc)
        m1 = EntityMention(id="mention_001", type=EntityType.PERSON, name="Rahul Sharma", confidence=0.95)
        m2 = EntityMention(id="mention_002", type=EntityType.PHONE, name="+919876543210", confidence=0.98)
        rel = Relationship(
            id="rel_001",
            source_entity_id="mention_001",
            relationship=RelationshipType.CALLED,
            target_entity_id="mention_002",
            confidence=0.9,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_001",
            evidence_snippet="Rahul called +919876543210",
            extracted_at=now,
        )
        res = ExtractionResult(
            document_id="doc_001",
            entities=[m1, m2],
            relationships=[rel],
        )
        validated = validate_extraction_result(res)
        self.assertEqual(validated.document_id, "doc_001")
        self.assertEqual(len(validated.entities), 2)
        self.assertEqual(len(validated.relationships), 1)

    def test_valid_empty_extraction_result(self):
        res = ExtractionResult(
            document_id="doc_empty",
            entities=[],
            relationships=[],
        )
        validated = validate_extraction_result(res)
        self.assertEqual(validated.document_id, "doc_empty")
        self.assertEqual(len(validated.entities), 0)
        self.assertEqual(len(validated.relationships), 0)

    def test_valid_partial_extraction_result(self):
        m1 = EntityMention(id="mention_001", type=EntityType.PERSON, name="Rahul Sharma", confidence=0.95)
        res = ExtractionResult(
            document_id="doc_001",
            entities=[m1],
            relationships=[],
        )
        validated = validate_extraction_result(res)
        self.assertEqual(len(validated.entities), 1)
        self.assertEqual(len(validated.relationships), 0)

    def test_duplicate_mention_ids_rejected(self):
        m1 = EntityMention(id="mention_001", type=EntityType.PERSON, name="Rahul Sharma", confidence=0.95)
        m2 = EntityMention(id="mention_001", type=EntityType.PERSON, name="Duplicate Mention", confidence=0.90)
        with self.assertRaises(ValidationError) as ctx:
            ExtractionResult(
                document_id="doc_001",
                entities=[m1, m2],
                relationships=[],
            )
        self.assertIn("duplicate", str(ctx.exception).lower())

    def test_duplicate_relationship_ids_rejected(self):
        now = datetime.now(timezone.utc)
        m1 = EntityMention(id="mention_001", type=EntityType.PERSON, name="Rahul Sharma", confidence=0.95)
        m2 = EntityMention(id="mention_002", type=EntityType.PHONE, name="+919876543210", confidence=0.98)
        rel1 = Relationship(
            id="rel_001",
            source_entity_id="mention_001",
            relationship=RelationshipType.CALLED,
            target_entity_id="mention_002",
            confidence=0.9,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_001",
            evidence_snippet="call 1",
            extracted_at=now,
        )
        rel2 = Relationship(
            id="rel_001",
            source_entity_id="mention_001",
            relationship=RelationshipType.CALLED,
            target_entity_id="mention_002",
            confidence=0.8,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_001",
            evidence_snippet="call 2",
            extracted_at=now,
        )
        with self.assertRaises(ValidationError) as ctx:
            ExtractionResult(
                document_id="doc_001",
                entities=[m1, m2],
                relationships=[rel1, rel2],
            )
        self.assertIn("duplicate", str(ctx.exception).lower())

    def test_referential_integrity_unknown_source_entity(self):
        now = datetime.now(timezone.utc)
        m2 = EntityMention(id="mention_002", type=EntityType.PHONE, name="+919876543210", confidence=0.98)
        rel = Relationship(
            id="rel_001",
            source_entity_id="mention_999",  # Not in entities
            relationship=RelationshipType.CALLED,
            target_entity_id="mention_002",
            confidence=0.9,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_001",
            evidence_snippet="call",
            extracted_at=now,
        )
        with self.assertRaises(ValidationError) as ctx:
            ExtractionResult(
                document_id="doc_001",
                entities=[m2],
                relationships=[rel],
            )
        self.assertIn("mention_999", str(ctx.exception))

    def test_referential_integrity_unknown_target_entity(self):
        now = datetime.now(timezone.utc)
        m1 = EntityMention(id="mention_001", type=EntityType.PERSON, name="Rahul Sharma", confidence=0.95)
        rel = Relationship(
            id="rel_001",
            source_entity_id="mention_001",
            relationship=RelationshipType.CALLED,
            target_entity_id="mention_888",  # Not in entities
            confidence=0.9,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_001",
            evidence_snippet="call",
            extracted_at=now,
        )
        with self.assertRaises(ValidationError) as ctx:
            ExtractionResult(
                document_id="doc_001",
                entities=[m1],
                relationships=[rel],
            )
        self.assertIn("mention_888", str(ctx.exception))

    def test_source_document_id_mismatch_rejected(self):
        now = datetime.now(timezone.utc)
        m1 = EntityMention(id="mention_001", type=EntityType.PERSON, name="Rahul Sharma", confidence=0.95)
        m2 = EntityMention(id="mention_002", type=EntityType.PHONE, name="+919876543210", confidence=0.98)
        rel = Relationship(
            id="rel_001",
            source_entity_id="mention_001",
            relationship=RelationshipType.CALLED,
            target_entity_id="mention_002",
            confidence=0.9,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_DIFFERENT",  # Mismatched
            evidence_snippet="call",
            extracted_at=now,
        )
        with self.assertRaises(ValidationError) as ctx:
            ExtractionResult(
                document_id="doc_001",
                entities=[m1, m2],
                relationships=[rel],
            )
        self.assertIn("source_document_id", str(ctx.exception))

    def test_extra_forbidden_fields_rejected(self):
        for forbidden in ["case_id", "graph_payload", "prediction_response", "ml_version"]:
            with self.assertRaises(ValidationError):
                ExtractionResult.model_validate({
                    "document_id": "doc_001",
                    "entities": [],
                    "relationships": [],
                    forbidden: "disallowed",
                })


class TestNegativeContractMatrix(unittest.TestCase):
    """Explicit tests for all 15 negative contract conditions specified in prompt."""

    def test_1_invalid_entity_type(self):
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m1", "type": "WEAPON", "name": "Gun", "confidence": 0.9})

    def test_2_invalid_relationship_type(self):
        now = datetime.now(timezone.utc).isoformat()
        with self.assertRaises(ValidationError):
            Relationship.model_validate({
                "id": "r1",
                "source_entity_id": "m1",
                "relationship": "STOLE_FROM",
                "target_entity_id": "m2",
                "confidence": 0.8,
                "status": "INFERRED",
                "source_document_id": "doc_1",
                "evidence_snippet": "ev",
                "extracted_at": now,
            })

    def test_3_invalid_pattern_type(self):
        with self.assertRaises(ValidationError):
            Pattern.model_validate({
                "id": "p1",
                "type": "TERROR_NETWORK",
                "severity": "HIGH",
                "status": "INFERRED",
                "entities": ["e1"],
                "explanation": "exp",
                "evidence_ids": ["ev1"],
            })

    def test_4_invalid_lead_priority(self):
        with self.assertRaises(ValidationError):
            Lead.model_validate({
                "id": "l1",
                "type": "FINANCIAL_NETWORK",
                "priority": "CRITICAL",
                "title": "Lead",
                "explanation": "Exp",
                "entity_ids": ["e1"],
                "evidence_ids": ["ev1"],
            })

    def test_5_detected_status_rejected_across_models(self):
        now = datetime.now(timezone.utc).isoformat()
        # Relationship rejects DETECTED
        with self.assertRaises(ValidationError):
            Relationship.model_validate({
                "id": "r1",
                "source_entity_id": "m1",
                "relationship": "CALLED",
                "target_entity_id": "m2",
                "confidence": 0.8,
                "status": "DETECTED",
                "source_document_id": "doc_1",
                "evidence_snippet": "ev",
                "extracted_at": now,
            })
        # Pattern rejects DETECTED
        with self.assertRaises(ValidationError):
            Pattern.model_validate({
                "id": "p1",
                "type": "CIRCULAR_TRANSACTION",
                "severity": "HIGH",
                "status": "DETECTED",
                "entities": ["e1"],
                "explanation": "exp",
                "evidence_ids": ["ev1"],
            })
        # Lead rejects DETECTED
        with self.assertRaises(ValidationError):
            Lead.model_validate({
                "id": "l1",
                "type": "FINANCIAL_NETWORK",
                "priority": "HIGH",
                "status": "DETECTED",
                "title": "Lead",
                "explanation": "Exp",
                "entity_ids": ["e1"],
                "evidence_ids": ["ev1"],
            })

    def test_6_confidence_less_than_zero(self):
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m1", "type": "PERSON", "name": "A", "confidence": -0.5})

    def test_7_confidence_greater_than_one(self):
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m1", "type": "PERSON", "name": "A", "confidence": 1.5})

    def test_8_missing_required_field(self):
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"type": "PERSON", "name": "A", "confidence": 0.9})

    def test_9_wrong_datatype(self):
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m1", "type": "PERSON", "name": "A", "confidence": "high"})
        with self.assertRaises(ValidationError):
            ResolutionProposal.model_validate({
                "canonical_entity_id": "c1",
                "mention_id": "m1",
                "confidence": 0.9,
                "signals": "name_similarity",  # Should be list
            })

    def test_10_malformed_datetime(self):
        with self.assertRaises(ValidationError):
            Relationship.model_validate({
                "id": "r1",
                "source_entity_id": "m1",
                "relationship": "CALLED",
                "target_entity_id": "m2",
                "confidence": 0.8,
                "status": "INFERRED",
                "source_document_id": "doc_1",
                "evidence_snippet": "ev",
                "extracted_at": "not-a-valid-datetime",
            })

    def test_11_malformed_nested_object(self):
        with self.assertRaises(ValidationError):
            ExtractionResult.model_validate({
                "document_id": "doc_1",
                "entities": [{"id": "m1", "type": "INVALID_TYPE", "name": "A", "confidence": 0.9}],
                "relationships": [],
            })

    def test_12_unsupported_extra_field_forbidden(self):
        with self.assertRaises(ValidationError):
            Lead.model_validate({
                "id": "l1",
                "type": "FINANCIAL_NETWORK",
                "priority": "HIGH",
                "title": "Lead",
                "explanation": "Exp",
                "entity_ids": ["e1"],
                "evidence_ids": ["ev1"],
                "unsupported_extra": "rejected",
            })

    def test_13_invalid_identifier_empty_string(self):
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "", "type": "PERSON", "name": "A", "confidence": 0.9})
        with self.assertRaises(ValidationError):
            ExtractionResult.model_validate({"document_id": "", "entities": [], "relationships": []})

    def test_14_invalid_null_for_required_field(self):
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m1", "type": None, "name": "A", "confidence": 0.9})
        with self.assertRaises(ValidationError):
            EntityMention.model_validate({"id": "m1", "type": "PERSON", "name": None, "confidence": 0.9})

    def test_15_malformed_extraction_result_dangling_reference(self):
        now = datetime.now(timezone.utc).isoformat()
        with self.assertRaises(ValidationError):
            ExtractionResult.model_validate({
                "document_id": "doc_1",
                "entities": [{"id": "m1", "type": "PERSON", "name": "A", "confidence": 0.9}],
                "relationships": [
                    {
                        "id": "r1",
                        "source_entity_id": "m1",
                        "relationship": "CALLED",
                        "target_entity_id": "m_NONEXISTENT",
                        "confidence": 0.8,
                        "status": "INFERRED",
                        "source_document_id": "doc_1",
                        "evidence_snippet": "ev",
                        "extracted_at": now,
                    }
                ],
            })


class TestJsonSerializationAndRoundTrip(unittest.TestCase):
    """Test serialization of ML outputs to JSON, parsing, and re-validation."""

    def test_entity_mention_json_roundtrip(self):
        original = EntityMention(id="mention_001", type=EntityType.PERSON, name="Rahul Sharma", confidence=0.96)
        json_str = original.model_dump_json()
        parsed = json.loads(json_str)
        revalidated = EntityMention.model_validate(parsed)
        self.assertEqual(original.model_dump(), revalidated.model_dump())

    def test_relationship_json_roundtrip(self):
        now = datetime(2026, 9, 13, 10, 30, 0, tzinfo=timezone.utc)
        original = Relationship(
            id="rel_001",
            source_entity_id="m_1",
            relationship=RelationshipType.CALLED,
            target_entity_id="m_2",
            confidence=0.95,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_001",
            evidence_snippet="Call snippet",
            extracted_at=now,
        )
        json_str = original.model_dump_json()
        parsed = json.loads(json_str)
        revalidated = Relationship.model_validate(parsed)
        self.assertEqual(original.id, revalidated.id)
        self.assertEqual(original.relationship, revalidated.relationship)
        self.assertEqual(original.extracted_at, revalidated.extracted_at)

    def test_resolution_proposal_json_roundtrip(self):
        original = ResolutionProposal(
            canonical_entity_id="entity_001",
            mention_id="mention_002",
            confidence=0.91,
            signals=[ResolutionSignal.NAME_SIMILARITY, ResolutionSignal.PHONE_MATCH],
        )
        json_str = original.model_dump_json()
        parsed = json.loads(json_str)
        revalidated = ResolutionProposal.model_validate(parsed)
        self.assertEqual(original.model_dump(), revalidated.model_dump())

    def test_pattern_json_roundtrip(self):
        original = Pattern(
            id="pat_001",
            type=PatternType.CIRCULAR_TRANSACTION,
            severity=Severity.HIGH,
            status=RelationshipStatus.INFERRED,
            entities=["ent_1", "ent_2", "ent_3"],
            explanation="Closed loop transfer detected",
            evidence_ids=["txn_1", "txn_2", "txn_3"],
        )
        json_str = original.model_dump_json()
        parsed = json.loads(json_str)
        revalidated = Pattern.model_validate(parsed)
        self.assertEqual(original.model_dump(), revalidated.model_dump())

    def test_lead_json_roundtrip(self):
        original = Lead(
            id="lead_001",
            type=LeadType.FINANCIAL_NETWORK,
            priority=LeadPriority.HIGH,
            status=LeadStatus.REVIEW_REQUIRED,
            title="Investigate circular flow",
            explanation="Three accounts transferred money in a loop.",
            entity_ids=["ent_1", "ent_2", "ent_3"],
            evidence_ids=["txn_1", "txn_2", "txn_3"],
            priority_score=0.88,
        )
        json_str = original.model_dump_json()
        parsed = json.loads(json_str)
        revalidated = Lead.model_validate(parsed)
        self.assertEqual(original.model_dump(), revalidated.model_dump())

    def test_extraction_result_json_roundtrip(self):
        now = datetime(2026, 9, 13, 11, 0, 0, tzinfo=timezone.utc)
        m1 = EntityMention(id="mention_001", type=EntityType.PERSON, name="Rahul Sharma", confidence=0.95)
        m2 = EntityMention(id="mention_002", type=EntityType.PHONE, name="+919876543210", confidence=0.98)
        rel = Relationship(
            id="rel_001",
            source_entity_id="mention_001",
            relationship=RelationshipType.CALLED,
            target_entity_id="mention_002",
            confidence=0.92,
            status=RelationshipStatus.INFERRED,
            source_document_id="doc_001",
            evidence_snippet="Rahul called +919876543210",
            extracted_at=now,
        )
        original = ExtractionResult(
            document_id="doc_001",
            entities=[m1, m2],
            relationships=[rel],
        )
        json_str = original.model_dump_json()
        parsed = json.loads(json_str)
        revalidated = ExtractionResult.model_validate(parsed)
        self.assertEqual(original.document_id, revalidated.document_id)
        self.assertEqual(len(original.entities), len(revalidated.entities))
        self.assertEqual(len(original.relationships), len(revalidated.relationships))

    def test_no_python_only_objects_in_json(self):
        """Ensure no sets, functions, or custom objects leak into output JSON."""
        now = datetime.now(timezone.utc)
        m1 = EntityMention(id="m_1", type=EntityType.PERSON, name="Alice", confidence=0.9)
        res = ExtractionResult(document_id="doc_1", entities=[m1], relationships=[])
        dumped = json.loads(res.model_dump_json())
        # All dictionary values must be primitive types (str, float, int, bool, list, dict, None)
        allowed_types = (str, float, int, bool, list, dict, type(None))
        self.assertTrue(all(isinstance(v, allowed_types) for v in dumped.values()))


class TestPhase10PipelineContractIntegration(unittest.TestCase):
    """Verify that actual Phase 10 pipeline outputs satisfy all contract schemas."""

    def test_1_document_with_entities(self):
        text = "Vikram Malhotra contacted Sunita Rao in Mumbai."
        result = process_document("doc_001", text)
        self.assertIsInstance(result, ExtractionResult)
        # JSON roundtrip validation
        json_str = result.model_dump_json()
        revalidated = ExtractionResult.model_validate(json.loads(json_str))
        self.assertEqual(revalidated.document_id, "doc_001")
        self.assertGreater(len(revalidated.entities), 0)

    def test_2_document_with_relationships(self):
        text = "Vikram Malhotra (+919876543210) works for Apex Industries in Mumbai."
        result = process_document("doc_002", text)
        self.assertIsInstance(result, ExtractionResult)
        # Verify relationships refer only to extracted entities
        entity_ids = {e.id for e in result.entities}
        for rel in result.relationships:
            self.assertIn(rel.source_entity_id, entity_ids)
            self.assertIn(rel.target_entity_id, entity_ids)
            self.assertEqual(rel.source_document_id, "doc_002")

    def test_3_document_with_transactions(self):
        txns = [
            {"sender": "ACC_111", "recipient": "ACC_222", "amount": 25000.0, "currency": "INR", "transaction_time": "2026-09-10T10:00:00", "record_id": "txn_001"},
            {"sender": "ACC_222", "recipient": "ACC_333", "amount": 24000.0, "currency": "INR", "transaction_time": "2026-09-11T12:00:00", "record_id": "txn_002"},
        ]
        result = process_document("doc_003", "", transactions=txns, return_full_analysis=True)
        self.assertIsInstance(result["extraction_result"], ExtractionResult)
        for e in result["entities"]:
            validate_entity_mention(e)
        for r in result["relationships"]:
            validate_relationship(r)

    def test_4_document_with_cdrs(self):
        cdrs = [
            {"caller": "+919876543210", "callee": "+919876543211", "duration": 120, "call_time": "2026-09-12T14:00:00", "record_id": "cdr_001"},
        ]
        result = process_document("doc_004", "", cdrs=cdrs, return_full_analysis=True)
        self.assertIsInstance(result["extraction_result"], ExtractionResult)
        # Verify CDR caller and receiver exist as entities
        names = {e.name for e in result["entities"]}
        self.assertIn("+919876543210", names)
        self.assertIn("+919876543211", names)

    def test_5_circular_transaction_produces_valid_patterns(self):
        txns = [
            {"sender": "ACC_A", "recipient": "ACC_B", "amount": 50000.0, "currency": "INR", "transaction_time": "2026-09-01T10:00:00", "record_id": "t1"},
            {"sender": "ACC_B", "recipient": "ACC_C", "amount": 49000.0, "currency": "INR", "transaction_time": "2026-09-02T10:00:00", "record_id": "t2"},
            {"sender": "ACC_C", "recipient": "ACC_A", "amount": 48000.0, "currency": "INR", "transaction_time": "2026-09-03T10:00:00", "record_id": "t3"},
        ]
        result = process_document("doc_circ", "", transactions=txns, return_full_analysis=True)
        patterns = result["patterns"]
        self.assertGreater(len(patterns), 0)
        circ_patterns = [p for p in patterns if p.type == PatternType.CIRCULAR_TRANSACTION]
        self.assertGreater(len(circ_patterns), 0)
        for pat in patterns:
            validated_pat = validate_pattern(pat)
            self.assertEqual(validated_pat.status, RelationshipStatus.INFERRED)
            self.assertNotEqual(validated_pat.status.value, "DETECTED")
            # Verify JSON roundtrip
            json_str = validated_pat.model_dump_json()
            Pattern.model_validate(json.loads(json_str))

    def test_6_rapid_transfer_chain_produces_valid_patterns(self):
        txns = [
            {"sender": "ACC_X", "recipient": "ACC_Y", "amount": 100000.0, "currency": "INR", "transaction_time": "2026-09-10T10:00:00", "record_id": "t1"},
            {"sender": "ACC_Y", "recipient": "ACC_Z", "amount": 98000.0, "currency": "INR", "transaction_time": "2026-09-10T12:00:00", "record_id": "t2"},
        ]
        result = process_document("doc_rapid", "", transactions=txns, return_full_analysis=True)
        rapid_patterns = [p for p in result["patterns"] if p.type == PatternType.RAPID_TRANSFER_CHAIN]
        self.assertGreater(len(rapid_patterns), 0)
        for p in rapid_patterns:
            validate_pattern(p)

    def test_7_location_time_overlap_produces_valid_patterns(self):
        cdrs = [
            {"caller": "+919876543210", "callee": "+919876543219", "call_time": "2026-09-12T14:00:00", "location": "Connaught Place, New Delhi", "record_id": "c1"},
            {"caller": "+919876543211", "callee": "+919876543218", "call_time": "2026-09-12T14:30:00", "location": "Connaught Place, New Delhi", "record_id": "c2"},
        ]
        result = process_document("doc_overlap", "", cdrs=cdrs, return_full_analysis=True)
        overlap_patterns = [p for p in result["patterns"] if p.type == PatternType.LOCATION_TIME_OVERLAP]
        self.assertGreater(len(overlap_patterns), 0)
        for p in overlap_patterns:
            validate_pattern(p)

    def test_8_patterns_producing_leads_conforms_to_contract(self):
        txns = [
            {"sender": "ACC_A", "recipient": "ACC_B", "amount": 50000.0, "currency": "INR", "transaction_time": "2026-09-01T10:00:00", "record_id": "t1"},
            {"sender": "ACC_B", "recipient": "ACC_C", "amount": 49000.0, "currency": "INR", "transaction_time": "2026-09-02T10:00:00", "record_id": "t2"},
            {"sender": "ACC_C", "recipient": "ACC_A", "amount": 48000.0, "currency": "INR", "transaction_time": "2026-09-03T10:00:00", "record_id": "t3"},
        ]
        result = process_document("doc_leads", "", transactions=txns, return_full_analysis=True)
        leads = result["leads"]
        self.assertGreater(len(leads), 0)
        for ld in leads:
            validated_ld = validate_lead(ld)
            self.assertEqual(validated_ld.status, LeadStatus.REVIEW_REQUIRED)
            self.assertIn(validated_ld.priority, [LeadPriority.LOW, LeadPriority.MEDIUM, LeadPriority.HIGH])
            # JSON roundtrip
            json_str = validated_ld.model_dump_json()
            Lead.model_validate(json.loads(json_str))

    def test_9_empty_document_handling(self):
        result = process_document("doc_empty", "")
        self.assertIsInstance(result, ExtractionResult)
        self.assertEqual(result.document_id, "doc_empty")
        self.assertEqual(len(result.entities), 0)
        self.assertEqual(len(result.relationships), 0)
        # JSON roundtrip
        json_str = result.model_dump_json()
        revalidated = ExtractionResult.model_validate(json.loads(json_str))
        self.assertEqual(revalidated.document_id, "doc_empty")

    def test_zero_database_uuids_and_zero_case_id(self):
        """Verify pipeline emits only ML staging identifiers and never invents database UUIDs or case_id."""
        text = "Vikram Sharma (+919876543210) transferred money to Amit Verma."
        result = process_document("doc_staging", text, return_full_analysis=True)
        envelope = result["extraction_result"]
        # Top-level has NO case_id
        envelope_dict = envelope.model_dump()
        self.assertNotIn("case_id", envelope_dict)

        # Entity IDs are staging strings
        for ent in envelope.entities:
            self.assertTrue(ent.id.startswith("mention_"), f"Entity ID '{ent.id}' should be staging ID")

        # Relationship IDs are staging strings
        for rel in envelope.relationships:
            self.assertTrue(rel.id.startswith("rel_"), f"Relationship ID '{rel.id}' should be staging ID")


class TestGoldenFixtureInvestigation(unittest.TestCase):
    """Deterministic multi-source investigation golden fixture test.
    
    Verifies a realistic investigation scenario:
    - Document A: Rahul Sharma (+919876543210) called Amit Kumar.
    - Document B: Amit Kumar works for Alpha Corp at Connaught Place, New Delhi.
    - Circular Transactions: ACC_A -> ACC_B -> ACC_C -> ACC_A within 5 days.
    - CDR: Rahul (+919876543210) called Amit (+919876543211).
    - Spatio-temporal records: Amit and Vijay co-located within 30 minutes.
    """

    def test_golden_fixture_end_to_end_contract(self):
        doc_text = (
            "Rahul Sharma (+919876543210) contacted Amit Kumar (+919876543211). "
            "Amit Kumar works for Alpha Corp located at Connaught Place, New Delhi."
        )
        txns = [
            {"sender": "ACC_ALPHA", "recipient": "ACC_BETA", "amount": 100000.0, "currency": "INR", "transaction_time": "2026-09-01T10:00:00", "record_id": "txn_g01"},
            {"sender": "ACC_BETA", "recipient": "ACC_GAMMA", "amount": 95000.0, "currency": "INR", "transaction_time": "2026-09-02T11:00:00", "record_id": "txn_g02"},
            {"sender": "ACC_GAMMA", "recipient": "ACC_ALPHA", "amount": 90000.0, "currency": "INR", "transaction_time": "2026-09-03T12:00:00", "record_id": "txn_g03"},
        ]
        cdrs = [
            {"caller": "+919876543210", "callee": "+919876543211", "duration": 180, "call_time": "2026-09-05T09:00:00", "location": "Connaught Place, New Delhi", "record_id": "cdr_g01"},
            {"caller": "+919876543211", "callee": "+919876543299", "duration": 90, "call_time": "2026-09-05T09:25:00", "location": "Connaught Place, New Delhi", "record_id": "cdr_g02"},
        ]

        result = process_document(
            "doc_golden_001",
            doc_text,
            transactions=txns,
            cdrs=cdrs,
            return_full_analysis=True,
        )

        # 1. Validate ExtractionResult envelope
        envelope = result["extraction_result"]
        self.assertIsInstance(envelope, ExtractionResult)
        validated_envelope = validate_extraction_result(envelope)
        self.assertEqual(validated_envelope.document_id, "doc_golden_001")

        # 2. Validate Entities
        entities = result["entities"]
        self.assertGreater(len(entities), 0)
        entity_ids = set()
        for ent in entities:
            validated_ent = validate_entity_mention(ent)
            entity_ids.add(validated_ent.id)
            self.assertIn(validated_ent.type, list(EntityType))
            self.assertTrue(0.0 <= validated_ent.confidence <= 1.0)
            self.assertNotIn(validated_ent.type.value, ["CRIMINAL", "SUSPECT"])

        # 3. Validate Relationships
        relationships = result["relationships"]
        for rel in relationships:
            validated_rel = validate_relationship(rel)
            self.assertIn(validated_rel.source_entity_id, entity_ids)
            self.assertIn(validated_rel.target_entity_id, entity_ids)
            self.assertIn(validated_rel.status, [RelationshipStatus.CONFIRMED, RelationshipStatus.INFERRED])
            self.assertNotEqual(validated_rel.status.value, "DETECTED")

        # 4. Validate Resolution Proposals
        proposals = result["resolution_proposals"]
        for prop in proposals:
            validated_prop = validate_resolution_proposal(prop)
            self.assertTrue(0.0 <= validated_prop.confidence <= 1.0)
            for sig in validated_prop.signals:
                self.assertIn(sig, list(ResolutionSignal))

        # 5. Validate Patterns
        patterns = result["patterns"]
        self.assertGreater(len(patterns), 0)
        circular_patterns = [p for p in patterns if p.type == PatternType.CIRCULAR_TRANSACTION]
        self.assertGreater(len(circular_patterns), 0)
        overlap_patterns = [p for p in patterns if p.type == PatternType.LOCATION_TIME_OVERLAP]
        self.assertGreater(len(overlap_patterns), 0)
        for pat in patterns:
            validated_pat = validate_pattern(pat)
            self.assertEqual(validated_pat.status, RelationshipStatus.INFERRED)
            self.assertIn(validated_pat.severity, [Severity.LOW, Severity.MEDIUM, Severity.HIGH])

        # 6. Validate Leads
        leads = result["leads"]
        self.assertGreater(len(leads), 0)
        for ld in leads:
            validated_ld = validate_lead(ld)
            self.assertEqual(validated_ld.status, LeadStatus.REVIEW_REQUIRED)
            self.assertIn(validated_ld.priority, [LeadPriority.LOW, LeadPriority.MEDIUM, LeadPriority.HIGH])

        # 7. Complete JSON Round-Trip Fidelity
        payload = {
            "extraction_result": envelope.model_dump(),
            "entities": [e.model_dump() for e in entities],
            "relationships": [r.model_dump() for r in relationships],
            "resolution_proposals": [p.model_dump() for p in proposals],
            "patterns": [p.model_dump() for p in patterns],
            "leads": [l.model_dump() for l in leads],
        }
        json_output = json.dumps(payload, default=str)
        deserialized = json.loads(json_output)

        # Re-validate all components from raw JSON dicts
        ExtractionResult.model_validate(deserialized["extraction_result"])
        for e_dict in deserialized["entities"]:
            EntityMention.model_validate(e_dict)
        for r_dict in deserialized["relationships"]:
            Relationship.model_validate(r_dict)
        for p_dict in deserialized["resolution_proposals"]:
            ResolutionProposal.model_validate(p_dict)
        for pat_dict in deserialized["patterns"]:
            Pattern.model_validate(pat_dict)
        for lead_dict in deserialized["leads"]:
            Lead.model_validate(lead_dict)


if __name__ == "__main__":
    unittest.main()
